const MAP_KEY='empire/map-v1.json',ACL_KEY='empire/editors-v1.json';
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');
function validData(d){if(!d||d.schemaVersion!==4||!Array.isArray(d.projects)||!Array.isArray(d.people)||d.projects.length>1000||d.people.length>300)return false;const ids=new Set(),pids=new Set();for(const p of d.people){if(typeof p.id!=='string'||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>150)return false;ids.add(p.id);if(p.photo&&!/^(assets\/[\w.-]+|data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+)$/.test(p.photo))return false}for(const p of d.projects){if(typeof p.id!=='string'||pids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>250||!Array.isArray(p.people)||p.people.some(id=>!ids.has(id)))return false;pids.add(p.id);if(p.photo&&!/^(assets\/[\w.-]+|data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+)$/.test(p.photo))return false;for(const m of p.materials||[]){try{if(!['https:','http:'].includes(new URL(m.url).protocol))return false}catch{return false}}}for(const p of d.projects){let q=p;const seen=new Set([p.id]);while(q.parentId){if(seen.has(q.parentId)||!pids.has(q.parentId))return false;seen.add(q.parentId);q=d.projects.find(x=>x.id===q.parentId)}}if(d.centerPhoto&&!/^(assets\/[\w.-]+|data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+)$/.test(d.centerPhoto))return false;return true}
function summarize(before,after){const messages=[];for(const [field,label] of [['projects','проект'],['people','участник']]){for(const p of after[field]){const previous=before[field].find(x=>x.id===p.id);if(!previous)messages.push('Добавлен '+label+': '+p.name);else if(JSON.stringify(previous)!==JSON.stringify(p))messages.push('Изменён '+label+': '+p.name)}for(const p of before[field])if(!after[field].some(x=>x.id===p.id))messages.push('Удалён '+label+': '+p.name)}if(before.title!==after.title)messages.push('Название карты');if(before.centerPhoto!==after.centerPhoto)messages.push('Главная фотография');if(JSON.stringify(before.portraitPositions)!==JSON.stringify(after.portraitPositions))messages.push('Позиции портретов');return messages.join('; ').slice(0,400)||'Сохранение карты'}
async function read(bucket,key){const object=await bucket.get(key);return {object,value:object?await object.json():null}}
async function save(bucket,key,value,object){const headers=new Headers();if(object)headers.set('If-Match',object.httpEtag);else headers.set('If-None-Match','*');return bucket.put(key,JSON.stringify(value),{onlyIf:headers,httpMetadata:{contentType:'application/json'}})}
async function identify(request,env){const raw=request.headers.get('authorization')?.replace(/^Bearer /,'')||'';if(!raw||raw.length>200)return {role:'viewer'};const hash=await digest(raw);if(env.MAP_OWNER_KEY&&hash===await digest(env.MAP_OWNER_KEY))return {role:'owner',name:'Владелец',id:'owner'};const acl=(await read(env.BUCKET,ACL_KEY)).value||{editors:[]};const editor=acl.editors.find(e=>e.hash===hash&&!e.revokedAt);return editor?{role:'editor',name:editor.name,id:editor.id}:{role:'viewer'}}
export async function api(request,env,seed){try{if(!env.BUCKET)return json({error:'Серверное хранилище недоступно'},503);const url=new URL(request.url),path=url.pathname;const user=await identify(request,env);if(path==='/api/session')return json(user);if(request.method!=='GET'&&request.headers.get('origin')!==url.origin)return json({error:'Недопустимый источник запроса'},403);
if(/^\/api\/gallery-assets\/(ilya|denis|ivan|cover|kuznetsov|nikolay|alena|liona|maria)$/.test(path)&&request.method==='PUT'){if(user.role!=='owner')return json({error:'Только владелец может загружать оригиналы'},403);const bytes=await request.arrayBuffer();if(bytes.byteLength>4194304||bytes.byteLength<8)return json({error:'Неверный размер изображения'},400);const a=new Uint8Array(bytes);if(![137,80,78,71,13,10,26,10].every((v,i)=>a[i]===v))return json({error:'Требуется PNG'},400);await env.BUCKET.put('gallery/'+path.split('/').pop()+'.png',bytes,{httpMetadata:{contentType:'image/png'}});return json({ok:true,size:bytes.byteLength})}
if(path==='/api/map'){const {object,value}=await read(env.BUCKET,MAP_KEY);const state=value||{revision:0,data:seed,history:[]};if(request.method==='GET')return json({revision:state.revision,data:state.data,updatedAt:state.updatedAt||null});if(request.method!=='PUT')return json({error:'Метод не поддерживается'},405);if(user.role==='viewer')return json({error:'Нужно приглашение редактора'},403);const raw=await request.text();if(new TextEncoder().encode(raw).length>1048576)return json({error:'Карта превышает 1 МБ. Используйте фотографии меньшего размера.'},413);let input;try{input=JSON.parse(raw)}catch{return json({error:'Некорректные данные'},400)}if(input.revision!==state.revision)return json({error:'Карту уже изменил другой участник',revision:state.revision},409);if(!validData(input.data))return json({error:'Некорректная структура карты'},400);const now=new Date().toISOString(),next={revision:state.revision+1,data:input.data,updatedAt:now,history:[{revision:state.revision,data:state.data,at:now,author:user.name,summary:summarize(state.data,input.data)},...state.history].slice(0,10)};if(!await save(env.BUCKET,MAP_KEY,next,object))return json({error:'Конфликт изменений. Загрузите актуальную карту.'},409);return json({revision:next.revision,updatedAt:now})}
if(path==='/api/history'){if(user.role==='viewer')return json({error:'Нет доступа'},403);const state=(await read(env.BUCKET,MAP_KEY)).value;return json({history:(state?.history||[]).map(({data,...item})=>item)})}
if(path==='/api/restore'&&request.method==='POST'){if(user.role!=='owner')return json({error:'Восстановление доступно владельцу'},403);const input=await request.json(),{object,value}=await read(env.BUCKET,MAP_KEY);if(!value||input.revision!==value.revision)return json({error:'Карта уже обновилась'},409);const entry=value.history.find(h=>h.revision===input.targetRevision);if(!entry)return json({error:'Версия не найдена'},404);const now=new Date().toISOString(),next={revision:value.revision+1,data:entry.data,updatedAt:now,history:[{revision:value.revision,data:value.data,at:now,author:user.name,summary:'Восстановление версии '+entry.revision},...value.history].slice(0,10)};if(!await save(env.BUCKET,MAP_KEY,next,object))return json({error:'Конфликт изменений'},409);return json({revision:next.revision,data:next.data})}
if(path==='/api/editors'){if(user.role!=='owner')return json({error:'Приглашения доступны владельцу'},403);const {object,value}=await read(env.BUCKET,ACL_KEY),acl=value||{editors:[]};if(request.method==='GET')return json({editors:acl.editors.map(({hash,...e})=>e)});const input=await request.json();if(request.method==='POST'){if(acl.editors.filter(e=>!e.revokedAt).length>=50)return json({error:'Достигнут лимит редакторов'},400);const key=token(),editor={id:crypto.randomUUID(),name:String(input.name||'Редактор').trim().slice(0,80)||'Редактор',hash:await digest(key),createdAt:new Date().toISOString()};acl.editors.push(editor);if(!await save(env.BUCKET,ACL_KEY,acl,object))return json({error:'Повторите создание приглашения'},409);return json({id:editor.id,name:editor.name,key})}if(request.method==='DELETE'){const item=acl.editors.find(e=>e.id===input.id);if(!item)return json({error:'Приглашение не найдено'},404);item.revokedAt=new Date().toISOString();if(!await save(env.BUCKET,ACL_KEY,acl,object))return json({error:'Повторите отзыв приглашения'},409);return json({ok:true})}}
return json({error:'Не найдено'},404)}catch{return json({error:'Не удалось выполнить запрос. Попробуйте ещё раз.'},500)}}
