import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import fs from 'node:fs';import {api} from './api.mjs';
class Bucket{constructor(){this.items=new Map;this.seq=0}async get(k){const x=this.items.get(k);return x?{etag:x.tag,httpEtag:'"'+x.tag+'"',json:async()=>JSON.parse(x.raw)}:null}async put(k,raw,options){const prev=this.items.get(k),headers=options.onlyIf;if(headers.get('If-None-Match')==='*'&&prev)return null;if(headers.has('If-Match')&&headers.get('If-Match')!=='"'+prev?.tag+'"')return null;const value={raw,tag:String(++this.seq)};this.items.set(k,value);return {etag:value.tag}}}
const env={BUCKET:new Bucket,MAP_OWNER_KEY:'owner-test-key'},seed=JSON.parse(fs.readFileSync('web/data.js','utf8').split('=').slice(1).join('=').trim().replace(/;$/,''));
async function call(path,method='GET',body,key=''){const req=new Request('https://example.test'+path,{method,headers:{Origin:'https://example.test',...(key?{Authorization:'Bearer '+key}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const response=await api(req,env,seed);return {status:response.status,data:await response.json()}}
assert.equal((await call('/api/session')).data.role,'viewer');assert.equal((await call('/api/map','PUT',{revision:0,data:seed})).status,403);assert.equal((await call('/api/session','GET',null,'owner-test-key')).data.role,'owner');
const invite=await call('/api/editors','POST',{name:'Редактор'},'owner-test-key');assert.equal(invite.status,200);const key=invite.data.key;assert.equal((await call('/api/session','GET',null,key)).data.role,'editor');assert(!JSON.stringify((await call('/api/editors','GET',null,'owner-test-key')).data).includes(key));
assert.equal((await call('/api/map','PUT',{revision:0,data:seed},key)).status,200);assert.equal((await call('/api/map','PUT',{revision:0,data:seed},key)).status,409);assert.equal((await call('/api/history','GET',null,key)).data.history.length,1);assert.equal((await call('/api/history')).status,403);assert.equal((await call('/api/restore','POST',{revision:1,targetRevision:0},key)).status,403);assert.equal((await call('/api/restore','POST',{revision:1,targetRevision:0},'owner-test-key')).status,200);
const invalid=structuredClone(seed);invalid.projects[0].parentId=invalid.projects[0].id;assert.equal((await call('/api/map','PUT',{revision:2,data:invalid},key)).status,400);invalid.projects[0].parentId=null;invalid.people[0].photo='javascript:alert(1)';assert.equal((await call('/api/map','PUT',{revision:2,data:invalid},key)).status,400);
await call('/api/editors','DELETE',{id:invite.data.id},'owner-test-key');assert.equal((await call('/api/session','GET',null,key)).data.role,'viewer');assert.equal((await call('/api/map','PUT',{revision:2,data:seed},key)).status,403);
const badOrigin=new Request('https://example.test/api/map',{method:'PUT',headers:{Origin:'https://other.test',Authorization:'Bearer owner-test-key'},body:JSON.stringify({revision:2,data:seed})});assert.equal((await api(badOrigin,env,seed)).status,403);
const concurrent=await Promise.all([call('/api/map','PUT',{revision:2,data:seed},'owner-test-key'),call('/api/map','PUT',{revision:2,data:seed},'owner-test-key')]);assert.deepEqual(concurrent.map(x=>x.status).sort(),[200,409]);
console.log('PASS: public reads, authorized writes, invitation creation/revocation, history, owner-only restore, invalid data, origin checks and concurrent writes');
const artifact=fs.readFileSync('dist/server/index.js','utf8');const mod=await import('data:text/javascript;base64,'+Buffer.from(artifact).toString('base64'));const page=await mod.default.fetch(new Request('https://example.test/'),env);assert.equal(page.status,200);assert((await page.text()).includes('og:image'));assert.equal((await mod.default.fetch(new Request('https://example.test/assets/share-cover.jpg'),env)).status,200);console.log('PASS: Worker artifact serves HTML and sharing image');
